version: '3.6'

services:
  web:
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./public:/var/www/html
    depends_on:
        - php
        - db
    restart: always
  
  db:
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
    restart: always
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
